service: todo-app
frameworkVersion: '3'

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-api-gateway-throttling
  - serverless-s3-sync

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-1
  httpApi:
    cors:
      allowedOrigins:
        - "http://${self:custom.bucketName}.s3-website-ap-northeast-1.amazonaws.com"
        - "http://localhost:3000"

custom:
  apiGatewayThrottling:
    maxRequestsPerSecond: 10
    maxConcurrentRequests: 5
  bucketName: sls-todo-app
  s3Sync:
    buckets:
      - bucketName: ${self:custom.bucketName}
        localDir: static/build

functions:
  taskList:
    handler: src/taskHandler.list
    events:
      - httpApi:
          method: get
          path: /tasks
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
        Resource: 'arn:aws:dynamodb:*:*:table/tasks'

  taskPost:
    handler: src/taskHandler.post
    events:
      - httpApi:
          method: post
          path: /tasks
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: 'arn:aws:dynamodb:*:*:table/tasks'

  taskNotifier:
    handler: src/taskNotifier.handler
    events:
      - schedule: cron(0 0 * * ? *)
    environment:
      SLACK_WEBHOOK_URL: ${ssm:todo_slack_notifier_url}

resources:
  Resources:
    TasksDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tasks
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    StaticSiteS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html

    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSiteS3Bucket
        PolicyDocument:
          Statement: 
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource:
                "arn:aws:s3:::${self:custom.bucketName}/*"
